debug_mode: false
domain_profile_url: https://www.domain.com.au/property-profile
chrome_path: /opt/google/chrome/chrome
telegram_token: 1234567890:ABCDEF
prop_image: div[data-testid="domain-propertyid-details"]
history_image: //*[contains(text(), 'Property history')]
popups:
  - html body div#__next div div div div.css-1a5nwms div.css-177de2j div.css-y0pdsh
image_divs:
  - div[data-testid="estimate-card"]
  - "#similar-properties"
