import datetime
from util import generate_hash
from fpdf import FPDF

def generate_pdf(property_address: str, property_url: str, image_names: list):
    """function to generate a pdf file from address and url of the property
    """
    pdf_file = f'pdfs/{generate_hash(property_address)}.pdf'

    # create a pdf document
    pdf = FPDF()

    # add a page
    pdf.add_page()

    # set the font and font size
    pdf.set_font("Arial", size=12)

    # add a title
    pdf.cell(200, 10, txt="Property Price History", ln=1, align="C")

    # add a line break
    pdf.ln(10)

    # add timestamp
    # get timestamp as string
    timestamp = '{:%Y-%b-%d %H:%M:%S}'.format(datetime.datetime.now())
    pdf.cell(200, 10, txt="Generated on: " + timestamp, ln=1, align="C")

    # add a line break
    pdf.ln(10)

    # add a line "Generated by https://t.me/propertyhelperbot"
    pdf.cell(200, 10, txt="Generated by https://t.me/propertyhelperbot", ln=1, align="C")

    # add a line break
    pdf.ln(10)

    # add the property address
    pdf.cell(200, 10, txt=property_address, ln=1, align="C")

    # add the property url
    pdf.cell(200, 10, txt=property_url, ln=1, align="C")

    # add the images, do not let images overlap one another
    for image_name in image_names:
        pdf.add_page()
        pdf.image(image_name, x=10, y=10, w=190, h=0, type='', link='')

    # output the pdf file
    pdf.output(pdf_file)

    return pdf_file